// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteCommand(arg1:string):Promise<main.CommandResult>;

export function Greet(arg1:string):Promise<string>;

export function OpenTerminalHere(arg1:string):Promise<main.CommandResult>;
